export const USER_REPOSITORY = 'USER_REPOSITORY';
export const AUTH_REPOSITORY = 'AUTH_REPOSITORY';
export const EMPLOYEE_REPOSITORY = 'EMPLOYEE_REPOSITORY';
export const RESTAURANT_REPOSITORY = 'RESTAURANT_REPOSITORY';
